# Reimagine

Our purpose today is to spot things that could help your workflow. The ideas is to reuse what works (for you and others), and ease off what doesn’t work


## What resonates for you from last week?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.1--->

*Revisit what was top-of-mind from last week. What else has emerged? What patterns, if any, are coming up for you?*

Waiting for google recording
 

 
:::

## Where within your workflow seems like a good place to start iterating?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What stands out about that place? Why are you motivated to focus on this part of your workflow?*

I'm motivated to focus on metadata and documentation because it is important for the future of a project.  
 

:::


## Think of a good workflow you’ve seen. What felt good about it? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*For example, what was it about how it was organized, how different people contributed, how it was communicated? Remember meetings are part of workflows too*

 Likley Mark Scheurelle's class and his projects. I also liked learning about ecological meta language. 

 


:::

## What have you seen or heard about that has you curious? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What are things you’d like to learn or reuse from what you’ve seen? Think from colleagues, talks, and examples online*

 I'm also interested in thinking through where I keep data as an organization. I don't like the solution of excel files in SharePoint project folders... 
 I don't know what other organziations do that have data storage systems. I also don't know what people do with hard copies of field sheets.

:::

## What are some of your values?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.3--->

*Think about something you enjoy doing. What qualities about yourself do you see coming through? What is important to you personally and professionally? How do you want to make people feel?*

Solving puzzles. Making sure the pieces all fit tightly, no gaps and skipped steps. No short cuts.

I want people to feel confident and encouraged. I like encouraging people. I also like laughter.
 

:::

## How do your values show up in your workflow, and how you interact with colleagues?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.3--->

*How do you show up in your daily life at work? For example, being on time, being organized, interacting with people.*

I think my value of clear communication and tight fitting work shows up in how I structure R projects, scripts, and comment code. My hope is that if I were abducted by an alien, someone could pick up where I left off without a headache.

I offer encouragment and words of affirmation, genuinely noticing it and sharing the positives that I observe. I also enjoy laugher, so I celebrate my funny colleagues and add humor where I can. 
 

:::


## What would it look like to connect your values more with your workflow?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.4--->

*Think about that place that seems like a good place to focus. What if you brought what you have seen and want to learn to that place, along with your values? You can draw this*

I mean, it would be awesome if humor and joy were an imbeded part of my work flow! But overall a workflow that was light, easily trasferable to others, and joyful would be amazing!  

 

:::
